DEF HIDE EQU $11
DEF SHOW EQU $15

; MissableObjects indexes (see data/maps/hide_show_data.asm)
; this is a list of the sprites that can be enabled/disabled during the game
; TODO: mark sprite constants with an X that are never used

	const_def
	const HS_PALLET_TOWN_OAK               ; 00
	const HS_LYING_OLD_MAN                 ; 01
	const HS_OLD_MAN_1                     ; 02
	const HS_OLD_MAN_2                     ; 03
	const HS_OFFICER_JENNY                 ; 04  ; New hide/show constant added by Vlad
	const HS_MUSEUM_GUY                    ; 05
	const HS_GYM_GUY                       ; 06
	const HS_CERULEAN_RIVAL                ; 07
	const HS_CERULEAN_ROCKET               ; 08
	const HS_CERULEAN_GUARD_1              ; 09
	const HS_CERULEAN_CAVE_GUY             ; 0A
	const HS_CERULEAN_GUARD_2              ; 0B
	const HS_SAFFRON_CITY_1                ; 0C
	const HS_SAFFRON_CITY_2                ; 0D
	const HS_SAFFRON_CITY_3                ; 0E
	const HS_SAFFRON_CITY_4                ; 0F
	const HS_SAFFRON_CITY_5                ; 10
	const HS_SAFFRON_CITY_6                ; 11
	const HS_SAFFRON_CITY_7                ; 12
	const HS_SAFFRON_CITY_8                ; 13
	const HS_SAFFRON_CITY_9                ; 14
	const HS_SAFFRON_CITY_A                ; 15
	const HS_SAFFRON_CITY_B                ; 16
	const HS_SAFFRON_CITY_C                ; 17
	const HS_SAFFRON_CITY_D                ; 18
	const HS_SAFFRON_CITY_E                ; 19
	const HS_SAFFRON_CITY_F                ; 1A
	const HS_ROUTE_2_ITEM_1                ; 1B
	const HS_ROUTE_2_ITEM_2                ; 1C
	const HS_ROUTE_4_ITEM                  ; 1D
	const HS_ROUTE_9_ITEM                  ; 1E
	const HS_ROUTE_12_SNORLAX              ; 1F
	const HS_ROUTE_12_ITEM_1               ; 20
	const HS_ROUTE_12_ITEM_2               ; 21
	const HS_ROUTE_15_ITEM                 ; 22
	const HS_ROUTE_16_SNORLAX              ; 23
	const HS_ROUTE_22_RIVAL_1              ; 24
	const HS_ROUTE_22_RIVAL_2              ; 25
	const HS_NUGGET_BRIDGE_GUY             ; 26
	const HS_ROUTE_24_ITEM                 ; 27
	const HS_ROUTE_25_ITEM                 ; 28
	const HS_DAISY_SITTING                 ; 29
	const HS_DAISY_WALKING                 ; 2A
	const HS_TOWN_MAP                      ; 2B
	const HS_OAKS_LAB_RIVAL                ; 2C
	const HS_STARTER_BALL_1                ; 2D
	const HS_OAKS_LAB_OAK_1                ; 2E
	const HS_POKEDEX_1                     ; 2F
	const HS_POKEDEX_2                     ; 30
	const HS_OAKS_LAB_OAK_2                ; 31
	const HS_VIRIDIANPOKECENTER_JESSIE     ; 32 ; New hide/show constant added by Vlad
	const HS_VIRIDIANPOKECENTER_JAMES      ; 33 ; New hide/show constant added by Vlad
	const HS_VIRIDIAN_GYM_GIOVANNI         ; 34
	const HS_VIRIDIAN_GYM_ITEM             ; 35
	const HS_OLD_AMBER                     ; 36
	const HS_CERULEAN_BULBASAUR            ; 37
	const HS_CERULEAN_CAVE_1F_ITEM_1       ; 38
	const HS_CERULEAN_CAVE_1F_ITEM_2       ; 39
	const HS_CERULEAN_CAVE_1F_ITEM_3       ; 3A
	const HS_CERULEAN_CAVE_1F_ITEM_4       ; 3B
	const HS_POKEMON_TOWER_2F_RIVAL        ; 3C
	const HS_POKEMON_TOWER_3F_ITEM         ; 3D
	const HS_POKEMON_TOWER_4F_ITEM_1       ; 3E
	const HS_POKEMON_TOWER_4F_ITEM_2       ; 3F
	const HS_POKEMON_TOWER_4F_ITEM_3       ; 40
	const HS_POKEMON_TOWER_5F_ITEM         ; 41
	const HS_POKEMON_TOWER_6F_ITEM_1       ; 42
	const HS_POKEMON_TOWER_6F_ITEM_2       ; 43
	const HS_POKEMON_TOWER_7F_JESSIE       ; 44
	const HS_POKEMON_TOWER_7F_JAMES        ; 45
	const HS_POKEMON_TOWER_7F_ROCKET1      ; 47
	const HS_POKEMON_TOWER_7F_ROCKET2      ; 48
	const HS_POKEMON_TOWER_7F_ROCKET3      ; 49
	const HS_POKEMON_TOWER_7F_ROCKET4      ; 4A
	const HS_POKEMON_TOWER_7F_MR_FUJI      ; 46
	const HS_MR_FUJIS_HOUSE_MR_FUJI        ; 4B
	const HS_CELADON_MANSION_EEVEE_GIFT    ; 4C
	const HS_GAME_CORNER_ROCKET            ; 4D
	const HS_WARDENS_HOUSE_ITEM            ; 4E
	const HS_POKEMON_MANSION_1F_ITEM_1     ; 4F
	const HS_POKEMON_MANSION_1F_ITEM_2     ; 50
	const HS_FIGHTING_DOJO_GIFT_1          ; 51
	const HS_FIGHTING_DOJO_GIFT_2          ; 52
	const HS_SILPH_CO_1F_RECEPTIONIST      ; 53
	const HS_VOLTORB_1                     ; 54
	const HS_VOLTORB_2                     ; 55
	const HS_VOLTORB_3                     ; 56
	const HS_ELECTRODE_1                   ; 57
	const HS_VOLTORB_4                     ; 58
	const HS_VOLTORB_5                     ; 59
	const HS_ELECTRODE_2                   ; 5A
	const HS_VOLTORB_6                     ; 5B
	const HS_ZAPDOS                        ; 5C
	const HS_POWER_PLANT_ITEM_1            ; 5D
	const HS_POWER_PLANT_ITEM_2            ; 5E
	const HS_POWER_PLANT_ITEM_3            ; 5F
	const HS_POWER_PLANT_ITEM_4            ; 60
	const HS_POWER_PLANT_ITEM_5            ; 61
	const HS_MOLTRES                       ; 62
	const HS_VICTORY_ROAD_2F_ITEM_1        ; 63
	const HS_VICTORY_ROAD_2F_ITEM_2        ; 64
	const HS_VICTORY_ROAD_2F_ITEM_3        ; 65
	const HS_VICTORY_ROAD_2F_ITEM_4        ; 66
	const HS_VICTORY_ROAD_2F_BOULDER       ; 67
	const HS_BILL_POKEMON                  ; 68
	const HS_BILL_1                        ; 69
	const HS_BILL_2                        ; 6A
	const HS_VIRIDIAN_FOREST_ITEM_1        ; 6B
	const HS_VIRIDIAN_FOREST_ITEM_2        ; 6C
	const HS_VIRIDIAN_FOREST_ITEM_3        ; 6D
	const HS_MT_MOON_1F_ITEM_1             ; 6E
	const HS_MT_MOON_1F_ITEM_2             ; 6F
	const HS_MT_MOON_1F_ITEM_3             ; 70
	const HS_MT_MOON_1F_ITEM_4             ; 71
;	const HS_MT_MOON_1F_ITEM_5             ; 6E ; Moving to another location (was Mt. Moon 1F Potion 2)
	const HS_MT_MOON_1F_ITEM_6             ; 72
	const HS_MT_MOON_B2F_JESSIE            ; 73
	const HS_MT_MOON_B2F_JAMES             ; 74
	const HS_MT_MOON_B2F_FOSSIL_1          ; 75
	const HS_MT_MOON_B2F_FOSSIL_2          ; 76
	const HS_MT_MOON_B2F_ITEM_1            ; 77
	const HS_MT_MOON_B2F_ITEM_2            ; 78
	const HS_SS_ANNE_2F_RIVAL              ; 79
	const HS_SS_ANNE_1F_ROOMS_ITEM         ; 7A
	const HS_SS_ANNE_2F_ROOMS_ITEM_1       ; 7B
	const HS_SS_ANNE_2F_ROOMS_ITEM_2       ; 7C
	const HS_SS_ANNE_B1F_ROOMS_ITEM_1      ; 7D
	const HS_SS_ANNE_B1F_ROOMS_ITEM_2      ; 7E
	const HS_SS_ANNE_B1F_ROOMS_ITEM_3      ; 7F
	const HS_VICTORY_ROAD_3F_ITEM_1        ; 80
	const HS_VICTORY_ROAD_3F_ITEM_2        ; 81
	const HS_VICTORY_ROAD_3F_BOULDER       ; 82
	const HS_ROCKET_HIDEOUT_B1F_ITEM_1     ; 83
	const HS_ROCKET_HIDEOUT_B1F_ITEM_2     ; 84
	const HS_ROCKET_HIDEOUT_B2F_ITEM_1     ; 85
	const HS_ROCKET_HIDEOUT_B2F_ITEM_2     ; 86
	const HS_ROCKET_HIDEOUT_B2F_ITEM_3     ; 87
	const HS_ROCKET_HIDEOUT_B2F_ITEM_4     ; 88
	const HS_ROCKET_HIDEOUT_B3F_ITEM_1     ; 89
	const HS_ROCKET_HIDEOUT_B3F_ITEM_2     ; 8A
	const HS_ROCKET_HIDEOUT_B4F_GIOVANNI   ; 8B
	const HS_ROCKET_HIDEOUT_B4F_JAMES      ; 8C
	const HS_ROCKET_HIDEOUT_B4F_JESSIE     ; 8D
	const HS_ROCKET_HIDEOUT_B4F_ITEM_1     ; 8E
	const HS_ROCKET_HIDEOUT_B4F_ITEM_2     ; 8F
	const HS_ROCKET_HIDEOUT_B4F_ITEM_3     ; 90
	const HS_ROCKET_HIDEOUT_B4F_ITEM_4     ; 91
	const HS_ROCKET_HIDEOUT_B4F_ITEM_5     ; 92
	const HS_SILPH_CO_2F_1                 ; 93 XXX never (de)activated?
	const HS_SILPH_CO_2F_2                 ; 94
	const HS_SILPH_CO_2F_3                 ; 95
	const HS_SILPH_CO_2F_4                 ; 96
	const HS_SILPH_CO_2F_5                 ; 97
	const HS_SILPH_CO_3F_1                 ; 98
	const HS_SILPH_CO_3F_2                 ; 99
	const HS_SILPH_CO_3F_ITEM              ; 9A
	const HS_SILPH_CO_4F_1                 ; 9B
	const HS_SILPH_CO_4F_2                 ; 9C
	const HS_SILPH_CO_4F_3                 ; 9D
	const HS_SILPH_CO_4F_ITEM_1            ; 9E
	const HS_SILPH_CO_4F_ITEM_2            ; 9F
	const HS_SILPH_CO_4F_ITEM_3            ; A0
	const HS_SILPH_CO_5F_1                 ; A1
	const HS_SILPH_CO_5F_2                 ; A2
	const HS_SILPH_CO_5F_3                 ; A3
	const HS_SILPH_CO_5F_4                 ; A4
	const HS_SILPH_CO_5F_ITEM_1            ; A5
	const HS_SILPH_CO_5F_ITEM_2            ; A6
	const HS_SILPH_CO_5F_ITEM_3            ; A7
	const HS_SILPH_CO_6F_1                 ; A8
	const HS_SILPH_CO_6F_2                 ; A9
	const HS_SILPH_CO_6F_3                 ; AA
	const HS_SILPH_CO_6F_ITEM_1            ; AB
	const HS_SILPH_CO_6F_ITEM_2            ; AC
	const HS_SILPH_CO_7F_1                 ; AD
	const HS_SILPH_CO_7F_2                 ; AE
	const HS_SILPH_CO_7F_3                 ; AF
	const HS_SILPH_CO_7F_4                 ; B0
	const HS_SILPH_CO_7F_RIVAL             ; B1
	const HS_SILPH_CO_7F_ITEM_1            ; B2
	const HS_SILPH_CO_7F_ITEM_2            ; B3
	const HS_SILPH_CO_7F_8                 ; B4 XXX sprite doesn't exist
	const HS_SILPH_CO_8F_1                 ; B5
	const HS_SILPH_CO_8F_2                 ; B6
	const HS_SILPH_CO_8F_3                 ; B7
	const HS_SILPH_CO_9F_1                 ; B8
	const HS_SILPH_CO_9F_2                 ; B9
	const HS_SILPH_CO_9F_3                 ; BA
	const HS_SILPH_CO_10F_1                ; BB
	const HS_SILPH_CO_10F_2                ; BC
	const HS_SILPH_CO_10F_3                ; BD XXX never (de)activated?
	const HS_SILPH_CO_10F_ITEM_1           ; BE
	const HS_SILPH_CO_10F_ITEM_2           ; BF
	const HS_SILPH_CO_10F_ITEM_3           ; C0
	const HS_SILPH_CO_11F_1                ; C1
	const HS_SILPH_CO_11F_JAMES            ; C2
	const HS_SILPH_CO_11F_2                ; C3
	const HS_SILPH_CO_11F_JESSIE           ; C4
	const HS_UNUSED_MAP_F4_1               ; C5 XXX sprite doesn't exist
	const HS_POKEMON_MANSION_2F_ITEM       ; C6
	const HS_POKEMON_MANSION_3F_ITEM_1     ; C7
	const HS_POKEMON_MANSION_3F_ITEM_2     ; C8
	const HS_POKEMON_MANSION_B1F_ITEM_1    ; C9
	const HS_POKEMON_MANSION_B1F_ITEM_2    ; CA
	const HS_POKEMON_MANSION_B1F_ITEM_3    ; CB
	const HS_POKEMON_MANSION_B1F_ITEM_4    ; CC
	const HS_POKEMON_MANSION_B1F_ITEM_5    ; CD
	const HS_SAFARI_ZONE_EAST_ITEM_1       ; CE
	const HS_SAFARI_ZONE_EAST_ITEM_2       ; CF
	const HS_SAFARI_ZONE_EAST_ITEM_3       ; D0
	const HS_SAFARI_ZONE_EAST_ITEM_4       ; D1
	const HS_SAFARI_ZONE_NORTH_ITEM_1      ; D2
	const HS_SAFARI_ZONE_NORTH_ITEM_2      ; D3
	const HS_SAFARI_ZONE_WEST_ITEM_1       ; D4
	const HS_SAFARI_ZONE_WEST_ITEM_2       ; D5
	const HS_SAFARI_ZONE_WEST_ITEM_3       ; D6
	const HS_SAFARI_ZONE_WEST_ITEM_4       ; D7
	const HS_SAFARI_ZONE_CENTER_ITEM       ; D8
	const HS_CERULEAN_CAVE_2F_ITEM_1       ; D9
	const HS_CERULEAN_CAVE_2F_ITEM_2       ; DA
	const HS_CERULEAN_CAVE_2F_ITEM_3       ; DB
	const HS_CERULEAN_CAVE_2F_ITEM_4       ; DC
	const HS_MEWTWO                        ; DD
	const HS_CERULEAN_CAVE_B1F_ITEM_1      ; DE
	const HS_CERULEAN_CAVE_B1F_ITEM_2      ; DF
	const HS_CERULEAN_CAVE_B1F_ITEM_3      ; E0
	const HS_CERULEAN_CAVE_B1F_ITEM_4      ; E1
	const HS_VICTORY_ROAD_1F_ITEM_1        ; E2
	const HS_VICTORY_ROAD_1F_ITEM_2        ; E3
	const HS_CHAMPIONS_ROOM_OAK            ; E4
	const HS_SEAFOAM_ISLANDS_1F_BOULDER_1  ; E5
	const HS_SEAFOAM_ISLANDS_1F_BOULDER_2  ; E6
	const HS_SEAFOAM_ISLANDS_B1F_BOULDER_1 ; E7
	const HS_SEAFOAM_ISLANDS_B1F_BOULDER_2 ; E8
	const HS_SEAFOAM_ISLANDS_B2F_BOULDER_1 ; E9
	const HS_SEAFOAM_ISLANDS_B2F_BOULDER_2 ; EA
	const HS_SEAFOAM_ISLANDS_B3F_BOULDER_1 ; EB
	const HS_SEAFOAM_ISLANDS_B3F_BOULDER_2 ; EC
	const HS_SEAFOAM_ISLANDS_B3F_BOULDER_3 ; ED
	const HS_SEAFOAM_ISLANDS_B3F_BOULDER_4 ; EE
	const HS_SEAFOAM_ISLANDS_B4F_BOULDER_1 ; EF
	const HS_SEAFOAM_ISLANDS_B4F_BOULDER_2 ; F0
	const HS_ARTICUNO                      ; F1
	const HS_DAISY_SITTING_COPY            ; F2
	const HS_DAISY_WALKING_COPY            ; F3
	const HS_TOWN_MAP_COPY                 ; F4

DEF NUM_HS_OBJECTS EQU const_value
